jobs:
  build_dll:
    env:
      VSDEVSH_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1
    runs-on: windows-2022
    steps:
    - name: Setup Env
      # Enable dev mode to allow symbolic links
      # Allow script execution
      # Remove conflicting names from PATH
      # Remove Android SDK from env to avoid Craft targeting Android
      run: |
        New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" -Name "AllowDevelopmentWithoutDevLicense" -PropertyType DWord -Value 1 -Force
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        Remove-Item -Path "C:\mingw64" -Recurse -Force -ErrorAction Ignore
        Remove-Item -Path "C:\Strawberry" -Recurse -Force -ErrorAction Ignore
        Remove-Item -Path "C:\Program Files\Git\bin\sh.exe" -Force
        [Environment]::SetEnvironmentVariable("ANDROID_SDK_ROOT", $null, "Machine")
        git config --global core.autocrlf false
        python -m pip install --upgrade certifi
      shell: pwsh
    - name: Install Craft
      run: |
        $env:ANDROID_SDK_ROOT = $null
        & $env:VSDEVSH_PATH -SkipAutomaticLocation -Arch amd64 -HostArch amd64
        Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/KDE/craft/master/setup/install_craft.ps1' -OutFile install_craft.ps1
        Unblock-File -Path .\install_craft.ps1
        & .\install_craft.ps1 -root C:\CraftRoot\ -use-defaults
      shell: pwsh
    - name: Craft 'em
      # Delete `cls` from script to prevent it crashing the terminal
      run: |
        $env:ANDROID_SDK_ROOT = $null
        & $env:VSDEVSH_PATH -SkipAutomaticLocation -Arch amd64 -HostArch amd64
        Unblock-File -Path C:\CraftRoot\craft\craftenv.ps1
        (Get-Content C:\CraftRoot\craft\craftenv.ps1) -replace '^cls$', '' | Set-Content C:\CraftRoot\craft\craftenv.ps1
        . C:\CraftRoot\craft\craftenv.ps1
        craft -v --ci-mode hunspell
        craft -v --ci-mode --options kde/frameworks/tier1/sonnet.useHunspell=True sonnet
        Get-ChildItem -Path C:\CraftRoot\bin -Recurse -Filter *.dll | Select-Object -ExpandProperty FullName
        Get-ChildItem -Path C:\CraftRoot\plugins -Recurse -Filter *.dll | Select-Object -ExpandProperty FullName
      shell: pwsh
    - name: Pick DLL
      run: |
        New-Item -Path .\artifact -ItemType Directory
        Copy-Item -Path C:\CraftRoot\bin\libhunspell*.dll -Destination .\artifact
        Copy-Item -Path C:\CraftRoot\plugins\kf6\sonnet\sonnet_hunspell.dll -Destination .\artifact
        Get-ChildItem -Path .\artifact
      shell: pwsh
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sonnet_hunspell_msvc
        path: .\artifact\*.dll
        retention-days: 1
    timeout-minutes: 15
name: Build sonnet_hunspell.dll
'on':
  workflow_dispatch:
permissions:
  contents: read
